### ISSUE TITLE
Arch Linux Support

### ISSUE THREAD

**Issue by KSPAtlas** [walkerje/C-Turtle#43]
I really like the idea of this repo, but I'd like a version that does not use the libx11-dev package (not available in arch). Can you please help?

**Comment by walkerje** [comment]
Unfortunately, X11 is a requirement of [CImg](https://cimg.eu/) displays at the moment. I am not particularly familiar with Arch Linux, but it appears that the general X11 package for Arch ([here](https://archlinux.org/packages/extra/x86_64/libx11/)) provides the same required headers and shared libraries provided by libx11-dev on other distributions ([here](https://packages.ubuntu.com/xenial/amd64/libx11-dev/filelist)). 

In the case of using Wayland rather than X, I would recommend taking a look at [XWayland](https://wayland.freedesktop.org/xserver.html) ([package](https://archlinux.org/packages/extra/x86_64/xorg-xwayland/)).

**Comment by walkerje** [comment]
As there was no follow-up to this issue, I have decided to close this.
